batch_size: 4
height: 64
learning_rate: 0.002
max_text_length: 256
model_path: Models/handwriting_recognition
train_epochs: 2
train_workers: 2
vocab: '!"#&''(),-.0123456789:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
width: 256
